version: '3.5'

volumes:
  mysql-8:

services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    restart: unless-stopped
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      #- MYSQL_DATABASE=dbname
    volumes:
      - mysql-8:/var/lib/mysql
